apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-login-config
  labels:
    app: login-service
data:
  MYSQL_DB_HOST: {{ .Values.login.mysql.host }}
  MYSQL_DB_PORT: "{{ .Values.login.mysql.port }}"
  MYSQL_DB_NAME: {{ .Values.login.mysql.database }}
  CHAT_ENDPOINT: "{{ .Values.login.chatEndpoint }}"
  SPRING_REDIS_HOST: {{ .Values.redis.host }}
  SPRING_REDIS_PORT: "{{ .Values.redis.port }}"