apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
  labels:
    app: profile-service
type: Opaque
data:
  mysql-username: {{ .Values.profile.mysql.user | b64enc }}
  mysql-password: {{ .Values.profile.mysql.password | b64enc }}
