apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.profile.service.name }}
  labels:
    app: profile-service
    project: containers
spec:
  type: {{ .Values.profile.service.type }}
  selector:
    app: profile-service
  ports:
  - port: {{ .Values.profile.service.port }}
    targetPort: {{ .Values.profile.service.targetPort }}
    protocol: TCP
