{{- if eq .Values.global.environment "gcp" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chat.service.name }}
  labels:
    project: containers
spec:
  type: {{ .Values.chat.service.type }}
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: {{ .Values.chat.service.port }}
      targetPort: {{ .Values.chat.service.targetPort }}
{{- end }}