global:
  environment: azure

profile:
  releaseName: spring-profile
  replicaCount: 2
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    cpuRequest: 200m
  repository: cmucloudcomputingchenanc.azurecr.io
  image: profile-service
  tag: latest
  service:
    name: spring-profile-service
    type: NodePort
    port: 80
    targetPort: 8080
  mysql:
    host: mysql-profile.default.svc.cluster.local
    port: 3306
    database: test
    user: profileUser
    password: ProfilePass456

login:
  releaseName: spring-login
  replicaCount: 3
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    cpuRequest: 200m
  repository: cmucloudcomputingchenanc.azurecr.io
  image: login
  tag: latest
  service:
    name: spring-login-service
    type: NodePort
    port: 80
    targetPort: 8080
  mysql:
    host: mysql-login.default.svc.cluster.local
    port: 3306
    database: test
    user: loginUser
    password: LoginPass456
  chatEndpoint: ""

redis:
  image: "redis:7"
  host: "redis-service"
  password: "SuperSecretRedisPassword"
  passwordSecret: "redis-secret"
  passwordKey: "REDIS_PASSWORD"
  port: "6379"
  containerPort: 6379
  topic: "/topic/messages"
  service:
    port: 6379
    targetPort: 6379
